---
title: "tits"
author: "Samyuktha"
date: "2024-11-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import Data

```{r}
tits <- read.csv('tit_clean.csv')
View(tits)
head(tits)
```
## Data Wrangling

```{r}
library(tidyverse)
tits_selected <- tits |> select(number_chicks_fledged_from_rear_nest, day_14_tarsus_length, day_14_weight, net_rearing_manipulation, hatch_year, rear_Box) |>
  filter(number_chicks_fledged_from_rear_nest > 0) |>
  mutate(number_chicks_after_manipulation = number_chicks_fledged_from_rear_nest + net_rearing_manipulation) |>
  filter(number_chicks_after_manipulation > 0)
View(tits_selected)
```

## LMMs

```{r}
library(lme4)
library(lmerTest)

lmm <- lmer(day_14_weight ~ number_chicks_after_manipulation + number_chicks_fledged_from_rear_nest + (1|hatch_year) + (1|rear_Box), data = tits_selected)
summary(lmm)

```

```{r}

lmm <- lmer(day_14_tarsus_length ~ number_chicks_after_manipulation + number_chicks_fledged_from_rear_nest + (1|hatch_year) + (1|rear_Box), data = tits_selected)
summary(lmm)
```
## Plots

```{r}
library(ggplot2)

plot_tarsus_length <- ggplot(data = tits_selected, aes(x = number_chicks_after_manipulation, y = day_14_tarsus_length))+ 
  geom_point() +
  geom_abline(slope = -0.0731, intercept = 16.704, colour = 'blue')
plot_tarsus_length

ggsave('plot_tarsus_length.png')
```

```{r}

plot_weight <- ggplot(data = tits_selected, aes(x = number_chicks_after_manipulation, y = day_14_weight))+ 
  geom_point() +
  geom_abline(slope = -0.177, intercept = 10.39, colour='red')
plot_weight

ggsave('plot_weight.png')
```

```{r}

plot_tarsus_length_fledged <- ggplot(data = tits_selected, aes(x = number_chicks_fledged_from_rear_nest, y = day_14_tarsus_length))+ 
  geom_point() 
plot_tarsus_length_fledged

ggsave('plot_fledged_tarsus_length.png')
```

```{r}

plot_weight_fledged <- ggplot(data = tits_selected, aes(x = number_chicks_fledged_from_rear_nest, y = day_14_weight))+ 
  geom_point() 
plot_weight_fledged

ggsave('plot_fledged_weight.png')
```

```{r}
plot_length_weight <- ggplot(data = tits_selected, aes(x = day_14_tarsus_length, y = day_14_weight))+ 
  geom_point() 
plot_length_weight

ggsave('plot_length_weight.png')
```



